instance_create_layer(x, y + 24, "Player", obj_CutsceneLevelCompleteP1)
with (obj_player1Land) instance_destroy()
with (obj_GunLandP1) instance_destroy()
with (obj_SpearP1) instance_destroy()
instance_destroy()